name: SBOM Upload

on:
  push:
    branches: ["stable"]
  pull_request:
    branches: ["stable"]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install sbom-tool
      run: |
        curl -Lo sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x sbom-tool

    - name: Generate SBOM
      run: |
        ./sbom-tool generate -b . -bc . -pn "YourProject" -pv "1.0.0" -ps "GitHub" -nsb "https://sca.example.com" -V Verbose

    - name: Send SBOM to SCA tool
      env:
        SCA_API_KEY: ${{ secrets.SCA_API_KEY }}
      run: |
        curl -X POST http:// 192.168.225.108:5000/api/upload \
        -H "Authorization: Bearer $SCA_API_KEY" \
        -H "Content-Type: application/json" \
        --data-binary "@_manifest/spdx_2.2/sbom.spdx.json" --insecure
